"""SessionPlan and ActionStep models."""

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class ActionStep(BaseModel):
    """One concrete thing to do during a session."""

    action: Literal[
        "browse_feed",
        "watch_stories",
        "like_post",
        "follow_user",
        "unfollow_user",
        "browse_profile",
        "browse_hashtag",
        "browse_explore",
        "comment_post",
        "send_dm",
        "post_feed",
        "post_reel",
        "post_story",
        "update_bio",
        "set_avatar",
        "view_notifications",
    ]
    params: dict = Field(default_factory=dict)
    # Soft caps for THIS step:
    max_count: int = 1
    max_duration_seconds: int | None = None


class SessionPlan(BaseModel):
    """
    A plan for a single session, generated by the orchestrator.
    The bot executes this plan step by step.
    """

    account_id: UUID
    intent: Literal["warmup", "engagement", "post", "health_check", "recovery"]
    target_duration_seconds: int = 600
    steps: list[ActionStep]
    # Account state caps for the session:
    daily_caps_remaining: dict[str, int] = Field(default_factory=dict)
    # Misc:
    posting_window: tuple[datetime, datetime] | None = None
    randomize_order: bool = False
    notes: str | None = None

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "account_id": "550e8400-e29b-41d4-a716-446655440000",
                    "intent": "warmup",
                    "target_duration_seconds": 300,
                    "steps": [
                        {
                            "action": "browse_feed",
                            "max_duration_seconds": 180,
                            "max_count": 20,
                        },
                        {"action": "watch_stories", "max_count": 4},
                        {"action": "browse_feed", "max_duration_seconds": 60},
                        {"action": "view_notifications", "max_count": 1},
                    ],
                    "daily_caps_remaining": {"likes": 0, "follows": 0, "comments": 0},
                }
            ]
        }
    }
